### ISSUE TITLE
SpotOrderStatus not working correctly

### ISSUE THREAD

**Issue by HackerFinance** [burakoner/Gate.IO.Api#2]
Hi, using your Gate.io library i've encountered a problem with SpotOrderStatus value inside the SubscribeToUserOrdersAsync subscription.
When you receive an update, the update.Data.Status property remain always settled at 0, instead of having a value between 1 and 3 (Open, Close, Cancelled).
I debugged the other fields inside the .Data object, the rest seems working, but i've to make some other test.
Anyway i suppose that probably when you receive an update from the websocket behind the scenes, some field is not filled correctly inside the .Data object.
Can you try to give it a watch?
Thanks again in advance and keep up the good work!

**Comment by burakoner** [comment]
In fact there no Numeric enumeration in Gate.Io. They send always string as "open","close" or "canceled". It's my mistake to set numeric values to enumeration. But there is a converter between data and enumeration. So It's not important if I set numeric values or not.
As you said data may be empty so in this case first item of enum will be set. I'll check stream data and will fix this issue. I'mm inform you

thanks for your feedback

**Comment by burakoner** [comment]
Gate.IO dont pass Order Status over websocket. 
https://www.gate.io/docs/developers/apiv4/ws/en/#server-notification-7

I'll release a new version today.

**Comment by burakoner** [comment]
1.3.3 released
https://github.com/burakoner/Gate.IO.Api/commit/601fa2c62226978cbc70c98dec88df1651c57326
https://www.nuget.org/packages/Gate.IO.Api/1.3.3

**Comment by HackerFinance** [comment]
Hi, i've tried the new update, but the problem is not solved at all, now instead of 0 you receive always null.
I've checked your link, the field you was searching for exists, it's not called "status", but "event", and it has 3 possible values: put, update and finish.
Checking inside your code, seems that your json property is called "status" and not "event", so i think the problem starts there.
After that, i think you should change the Converter for the enumerable, inserting the values "put", "update" and "finish", as wrote in Gate.io docs.
Let me know and thanks in advance.

**Comment by burakoner** [comment]
Yes. Because it uses shared Order response model with Rest Api

**Comment by HackerFinance** [comment]
The problem is that the field in the Gate.io server response is called "event", not "status". In this way, the json object is not wrapped correctly, because inside there's not a "status" field, and infact if you try it, everytime the Status property results null.

**Comment by HackerFinance** [comment]
Try to simulate with Gate.io a filled order event and see what you get in the Status property, you'll see null value.

**Comment by burakoner** [comment]
I'll use another model in next releases. But I need to say, You wont be able to see order status on updates. Because gate.io doesnt pass this parameter via websocket. You can check documentation.

https://www.gate.io/docs/developers/apiv4/ws/en/#server-notification-7

**Comment by HackerFinance** [comment]
Instead yes, Gate.io websocket passes the status of the order, it's the field called "event" inside the documentation, as i told you in my messages above. Check your documentation link, section Orders Channel, Server Notifications; in the parameters returned by the server there's a field called "event", that as already said can have 3 values, "put", "update" and "finish". You can notice that those values are the Open, Closed and Cancelled that you normally use. You should change your status json property calling it "event", and then modify the Converter of the Enumerable to manage the values "put", "update" and "finish". Hope it can help.

**Comment by burakoner** [comment]
Check Version 1.3.4 https://github.com/burakoner/Gate.IO.Api/commit/2b5457f322052bcff928c7a30ddbc11cfc877617 https://www.nuget.org/packages/Gate.IO.Api/1.3.4

**Comment by HackerFinance** [comment]
Ok, now the code seems ok at a first glance, i've to try it as soon as i'll be able to.

**Comment by HackerFinance** [comment]
Tested it and infact now it functions perfectly, problem solved, thank you!

**Comment by burakoner** [comment]
Great
