### ISSUE TITLE
Order Update object missing Side field

### ISSUE THREAD

**Issue by HackerFinance** [burakoner/Gate.IO.Api#3]
Hi, checking between Order Update properties inside the SubscribeToUserOrdersAsync subscription, i didn't find the Side property. Seems it's missing at all. Don't know if there are other missing or empty fields, maybe is better to check for all, but surely there's not the Order.Side property.

**Comment by HackerFinance** [comment]
I checked inside the SpotStreamOrderUpdate object and i can confirm that the Side property is missing.

**Comment by burakoner** [comment]
I've added both side and Quantity (amount) properties to model. Please check https://github.com/burakoner/Gate.IO.Api/commit/df4b7d0528e89928b0e2309de8fb4c9594b74cb1 and https://www.nuget.org/packages/Gate.IO.Api/1.3.5

**Comment by HackerFinance** [comment]
Tested the new update, all fine!
